name: vista

# global environment variables
env:
  POSTGRES_URL: "jdbc:postgresql://localhost:5432"

on: 
  push:
    branches: 
      - main
    
jobs:
  simple_commands:
    runs-on: ubuntu-latest
    
    steps:
      - name: List package
        run : ls -al
        
      - name: Whoami
        run : whoami
        
      - name: Create file
        run : echo "new file" > file.txt
        
      - name: List Los Angeles
        run : ls -la
        
      - name: Pipe commands
        run : echo "$USERNAME:$PASSWORD"
        env :
          USERNAME: "admin"
          PASSWORD: "adminpassword"
  
  git_clone:
    runs-on: ubuntu-latest
    needs  : [simple_commands] 
    
    steps:
      - name: List package
        run : |
          pwd
          ls -al
    
      - name: Git clone
        uses: actions/checkout@v1 
        
      - name: List package
        run : |
          pwd
          ls -al
          
      - name: Grant Permission
        run: chmod +x mvnw
          
      - name: Test
        run : ./mvnw test
          
#       - name: Test
#         run : |
#           cd /home/runner/work/security_test/security_test
#           mvnw test
