name: vista

# global environment variables
env:
  POSTGRES_URL: "jdbc:postgresql://localhost:5432"

on: 
  push:
    branches: 
      - main
    
jobs:
  simple_commands:
    runs-on: ubuntu-latest
    
    steps:
      - name: List package
        run : ls -al
        
      - name: Whoami
        run : whoami
        
      - name: Create file
        run : echo "new file" > file.txt
        
      - name: List Los Angeles
        run : ls -la
